import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Search, Menu } from 'lucide-react';
import { Toaster } from 'sonner';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        {children}
        
      {/* <Search />
      <Menu /> */}
      <Toaster/>
      {/* <Toast/> */}

      </body>
    </html>
  );
}
// className={`${geistSans.variable} ${geistMono.variable}`}